#!/usr/bin/env python3
"""
Generate rolling_cases CSV for the 3-way pipeline.

Usage:
  python3 make_cases_csv.py \
      --syzagent-dir /path/to/SyzAgent \
      --workdir-base /your/workdir/root \
      --output rolling_cases.csv \
      [--cases 1-50]          # range like "1-50" or "51-100" or "1-100"
      [--linux-template /path/to/linux/src]
      [--build-j 4] [--fuzz-j 2]

Output CSV format (for run_rolling_pipeline.py):
  case_id, dataset_xlsx, workdir_agent, workdir_baseline, workdir_proactive,
           build_j, fuzz_j [, linux_template]
"""

import argparse
import os


def main():
    ap = argparse.ArgumentParser(description="Generate 3-way pipeline CSV")
    ap.add_argument("--syzagent-dir", default=os.path.dirname(os.path.abspath(__file__)),
                    help="Path to SyzAgent repo root (default: this script's directory)")
    ap.add_argument("--workdir-base", required=True,
                    help="Base directory for workdirs (e.g. /home/user/work_real)")
    ap.add_argument("--output", required=True,
                    help="Output CSV path")
    ap.add_argument("--cases", default="1-100",
                    help="Case range like '1-50' or '51-100' (default: 1-100)")
    ap.add_argument("--linux-template", default="",
                    help="Optional: path to a pre-checked-out linux source tree to reuse")
    ap.add_argument("--build-j", type=int, default=4,
                    help="Build parallelism (default: 4)")
    ap.add_argument("--fuzz-j", type=int, default=2,
                    help="Fuzzer VM count per case (default: 2)")
    args = ap.parse_args()

    # Parse case range
    if "-" in args.cases:
        lo, hi = args.cases.split("-", 1)
        case_ids = list(range(int(lo), int(hi) + 1))
    else:
        case_ids = [int(args.cases)]

    dataset_dir = os.path.join(args.syzagent_dir, "generated_datasets", "syzdirect_100")
    workdir_agent     = os.path.join(args.workdir_base, "workdir_agent")
    workdir_baseline  = os.path.join(args.workdir_base, "workdir_baseline")
    workdir_proactive = os.path.join(args.workdir_base, "workdir_proactive")

    lines = [
        "# 3-way rolling pipeline CSV",
        "# Generated by make_cases_csv.py",
        f"# Cases: {args.cases}",
        f"# workdir_agent:     {workdir_agent}",
        f"# workdir_baseline:  {workdir_baseline}",
        f"# workdir_proactive: {workdir_proactive}",
        "#",
        "# case_id, dataset_xlsx, workdir_agent, workdir_baseline, workdir_proactive,"
        " build_j, fuzz_j [, linux_template]",
    ]

    skipped = []
    for cid in case_ids:
        xlsx = os.path.join(dataset_dir, f"case_{cid}.xlsx")
        if not os.path.exists(xlsx):
            skipped.append(cid)
            continue
        row = f"{cid}, {xlsx}, {workdir_agent}, {workdir_baseline}, {workdir_proactive}, {args.build_j}, {args.fuzz_j}"
        if args.linux_template:
            row += f", {args.linux_template}"
        lines.append(row)

    with open(args.output, "w") as f:
        f.write("\n".join(lines) + "\n")

    written = len(case_ids) - len(skipped)
    print(f"Wrote {written} cases → {args.output}")
    if skipped:
        print(f"  (skipped {len(skipped)} missing datasets: {skipped})")
    print(f"\nTo run the pipeline:")
    print(f"  python3 run_rolling_pipeline.py --cases-csv {args.output} --fuzz-hours 6 --fuzz-slots 3")


if __name__ == "__main__":
    main()
